[tools]
node = "24"
pnpm = "11.5.2"

[env]
_.file = ".env"

[tasks.dev]
run = "pnpm dev"

[tasks.ios]
run = "pnpm ios"

[tasks.android]
run = "pnpm android"

[tasks.web]
run = "pnpm web"

[tasks.format]
run = "pnpm format"

[tasks.lint]
run = "pnpm lint"

[tasks.type-check]
run = "pnpm type-check"

[tasks.doctor]
run = "pnpm doctor"
