name: Expo Build
on:
  workflow_call:
    inputs:
      eas-profile:
        required: true
        type: string
      platform:
        required: false
        type: string
        default: Android

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
    - name: 🏗 Setup repo
      uses: actions/checkout@v4

    - name: 🏗 Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'

    - name: 🏗 Install dependencies
      run: yarn install

    - name: 🏗 Setup Expo and EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    - name: 🏗 Build project
      run: eas build --profile "${{ inputs.eas-profile }}" --platform "${{ inputs.platform }}" --non-interactive --no-wait
