name: Run expo doctor
on:
  pull_request:
    branches:
      - main
jobs:
  expo-doctor:
    name: Run expo doctor
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - uses: pnpm/action-setup@v4
        with:
          version: 11.5.2
      - name: Enable Corepack
        run: corepack enable
      - name: Install packages
        run: pnpm install --frozen-lockfile
        working-directory: ./
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: expo doctor
        run: pnpm exec expo-doctor
        working-directory: ./
